version: "3.8"

services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./src/db/data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
  app:
    depends_on:
      - db
    build:
      context: ./src
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: todos
    command: ["./wait.sh"]
